Revert "Feature - Update return type on original util"
nickzuber-alt-but-cooler/test pull request #5
Opened 2023-04-01 20:30 UTC by nickzuber

Reverts nickzuber-alt-but-cooler/test#3

2023-04-01 20:37 UTC, nickzuber-alt-but-cooler approved these changes

2023-04-01 20:38 UTC, nickzuber reviewed
my own comment

2023-04-01 20:42 UTC, nickzuber reviewed
a review.

2023-04-01 20:44 UTC, nickzuber reviewed
another.

2023-04-01 20:47 UTC, nickzuber reviewed
one mroe.

2023-04-01 20:48 UTC, nickzuber reviewed
ghdf

2023-04-01 20:49 UTC, nickzuber reviewed
ggg

2023-04-01 20:53 UTC, nickzuber reviewed
czccc

2023-04-01 20:54 UTC, nickzuber reviewed
ok got it

2023-04-04 22:41 UTC, nickzuber reviewed
@nickzuber-alt-but-cooler hey

2023-04-04 23:02 UTC, nickzuber commented
fsdf

2023-04-04 23:03 UTC, nickzuber commented
df

2023-04-04 23:07 UTC, nickzuber commented
sfd

2023-04-05 02:56 UTC, nickzuber commented
gdfg

2023-04-05 02:57 UTC, nickzuber commented
dsdf

2023-05-20 19:50 UTC, nickzuber-alt-but-cooler commented
hey

2023-09-25 03:22 UTC, nickzuber-alt-but-cooler approved these changes

2023-09-25 03:22 UTC, nickzuber-alt-but-cooler commented on utils.ts
> +  return null
Maybe we can do a forward fix instead?

2023-09-25 03:25 UTC, nickzuber-alt-but-cooler requested changes

2023-09-25 03:25 UTC, nickzuber-alt-but-cooler commented on utils.ts
> -  return 123
Wait I like numbers

2023-09-25 03:35 UTC, nickzuber-alt-but-cooler commented
:)

2023-09-30 01:58 UTC, nickzuber-alt-but-cooler commented
@nickzuber yo

2023-10-02 03:29 UTC, nickzuber-alt-but-cooler commented
@nickzuber hi

2023-12-27 05:08 UTC, merged